### ISSUE TITLE
removing macrons recipe

### ISSUE THREAD

**Issue by aconser** [diyclassics/classics-cookbook#1]
I'm very excited for this new resource!  One question: for removing macrons from Latin text, why not decompose and remove the character? This is from my [prosody module for Greek](https://github.com/aconser/Greek-Poetry/blob/master/Greek_Prosody/prosody.py):
```
import unicodedata

MACRON = u'\u0304'
SHORT_MARK = u'\u0306'

def remove_length_markers (string):
    decomposed = unicodedata.normalize('NFD', string)
    decomposed = decomposed.replace(MACRON, '')
    decomposed = decomposed.replace(SHORT_MARK, '')
    return unicodedata.normalize('NFC', decomposed)
```
I'm curious how this would compare for time.

**Comment by diyclassics** [comment]
Thanks for the suggestion!—I've included it at the end of 'Recipe 3' and added a contributors line to the top of the notebook.

**Comment by aconser** [comment]
Thanks for giving my function a try, and I'm amazed by how much slower it is.  In the context of Greek it is a little more difficult, because macrons will not combine when there are other diacriticals (cf. James Tauber's very helpful [post](https://jktauber.com/2016/01/28/polytonic-greek-unicode-is-still-not-perfect/).  That said, I'll see about refactoring to do specific vowel replacements without having to decompose and recompose everything.  Thanks again!
